name = "cyber-synth"
license = "MIT"
licenselink = "https://github.com/yourusername/hugo-theme-cyber-synth/blob/master/LICENSE"
description = "A futuristic, cyberpunk-inspired Hugo theme with retrowave aesthetics and modern AI elements"
homepage = "https://github.com/yourusername/hugo-theme-cyber-synth"
tags = ["blog", "dark", "responsive", "modern", "cyberpunk", "retrowave", "futuristic", "tech", "ai", "cloud", "gaming", "music"]
features = ["blog", "responsive", "dark mode", "syntax highlighting", "custom shortcodes"]
min_version = "0.41.0"

[author]
  name = "Theme Creator"
  homepage = "https://github.com/yourusername"