baseurl = "https://www.evilurge.com/"
languageCode = "en-us"
theme = "analog-meets-digital"

[pagination]
  pagerSize = 12

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  contentTypeName = "posts"
  themeColor = "warm-gold"
  studioMode = true
  fullWidthTheme = false
  centerTheme = true
  description = "A tech blog about cloud, AI, and coding by Gilad Maoz"
  showThemeSelector = true
  showBuildInfo = true
  themeVersion = "2.0"

[languages]
  [languages.en]
    title = ">ShellGems_"
    subtitle = "All those small things"
    keywords = "nodejs firebase cloud edge python ai tech gaming music"
    copyright = "Gilad Maoz"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = ">ShellGems_"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "É•urls"
        name = "É•urls"
        url = "/curls"

    [[languages.en.menu.main]]
      identifier = "âž•.bashrc"
      name = "âž•.bashrc"
      url = "/bash"

    [[languages.en.menu.main]]
      identifier = "snippets"
      name = "snippets"
      url = "https://gist.github.com/evilUrge"


    [[languages.en.menu.main]]
      identifier = "ðŸ§” Who am I?"
      name = "ðŸ§” Who am I?"
      url = "/who-am-i"
