baseurl = "https://www.evilurge.com/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params]
  contentTypeName = "posts"
  themeColor = "red"
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = ">ShellGems_"
    subtitle = "All those small things"
    keywords = "nodejs firebase cloud edge python"
    copyright = "Gilad Maoz"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = ">ShellGems_"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "É•urls"
        name = "É•urls"
        url = "/curls"

    [[languages.en.menu.main]]
      identifier = "âž•.bashrc"
      name = "âž•.bashrc"
      url = "/bash"

    [[languages.en.menu.main]]
      identifier = "snippets"
      name = "snippets"
      url = "https://gist.github.com/evilUrge"


    [[languages.en.menu.main]]
      identifier = "ðŸ§” Who am I?"
      name = "ðŸ§” Who am I?"
      url = "/who-am-i"
