version: 2
jobs:
  deploy:
    filters:
      branches:
        only:
        - master
    docker:
    - image: circleci/node

    working_directory: ~/repo

    steps:
    - run:
        name: Set env params
        command: export NODE_ENV=production

    - checkout
    - run: sudo apt-get install hugo
    - run: hugo
    - run: npm install --production
    # deploy
    - run: node deploy.js


workflows:
  version: 2
  test_and_deploy:
    jobs:
    - deploy:
        filters:
          branches:
            only: master
