version: 2
jobs:
  deploy:
    filters:
      branches:
        only:
        - master
    docker:
    - image: circleci/node

    working_directory: ~/repo

    steps:
    - run:
        name: Set env params
        command: export NODE_ENV=production

    - checkout
    # Install the latest version of Hugo
    - run: cd ~ ; sudo curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep  browser_download_url | grep Linux-64bit.deb | grep -v extended | cut -d '"' -f 4 | wget -i -
    - run: sudo dpkg -i hugo*_Linux-64bit.deb
    # Generate static version of the blog
    - run: hugo
    # deploy
    - run: npm install --production
    - run: node deploy.js


workflows:
  version: 2
  test_and_deploy:
    jobs:
    - deploy:
        filters:
          branches:
            only: master
