name: docssite-deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.0'
      - name: Build
        run: hugo --minify
      - name: Deploy
        run: node_modules/firebase-tools/lib/bin/firebase.js deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}